version: '3.8'

services:
  database:
    image: mongo
    container_name: database
    restart: always
    ports:
      - "27017:27017"

  server:
    container_name: server
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017
      - MIGRATE_MONGO_URI=mongodb://database:27017